// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: models/proto/tx.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// specific message types
	Messages []*anypb.Any `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// transaction costs (fee)
	Fee *TxFee `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	// the signatures for the transaction
	Signatures []*TxSignature `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// memo attached to the transaction
	Memo string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (x *Tx) Reset() {
	*x = Tx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_models_proto_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Tx) GetMessages() []*anypb.Any {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Tx) GetFee() *TxFee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *Tx) GetSignatures() []*TxSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *Tx) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type TxFee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// gas limit
	GasWanted int64 `protobuf:"zigzag64,1,opt,name=gas_wanted,json=gasWanted,proto3" json:"gas_wanted,omitempty"`
	// gas fee details (<value><denomination>)
	GasFee string `protobuf:"bytes,2,opt,name=gas_fee,json=gasFee,proto3" json:"gas_fee,omitempty"`
}

func (x *TxFee) Reset() {
	*x = TxFee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxFee) ProtoMessage() {}

func (x *TxFee) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxFee.ProtoReflect.Descriptor instead.
func (*TxFee) Descriptor() ([]byte, []int) {
	return file_models_proto_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxFee) GetGasWanted() int64 {
	if x != nil {
		return x.GasWanted
	}
	return 0
}

func (x *TxFee) GetGasFee() string {
	if x != nil {
		return x.GasFee
	}
	return ""
}

type TxSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// public key associated with the signature
	PubKey *anypb.Any `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// the signature
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TxSignature) Reset() {
	*x = TxSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignature) ProtoMessage() {}

func (x *TxSignature) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignature.ProtoReflect.Descriptor instead.
func (*TxSignature) Descriptor() ([]byte, []int) {
	return file_models_proto_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TxSignature) GetPubKey() *anypb.Any {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *TxSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PubKeySecp256K1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PubKeySecp256K1) Reset() {
	*x = PubKeySecp256K1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_proto_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKeySecp256K1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeySecp256K1) ProtoMessage() {}

func (x *PubKeySecp256K1) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeySecp256K1.ProtoReflect.Descriptor instead.
func (*PubKeySecp256K1) Descriptor() ([]byte, []int) {
	return file_models_proto_tx_proto_rawDescGZIP(), []int{3}
}

func (x *PubKeySecp256K1) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_models_proto_tx_proto protoreflect.FileDescriptor

var file_models_proto_tx_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x02, 0x54, 0x78, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x03, 0x66,
	0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x78, 0x46, 0x65, 0x65,
	0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x78, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22, 0x3f, 0x0a, 0x05, 0x54, 0x78, 0x46, 0x65, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x73, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x12, 0x52, 0x09, 0x67, 0x61, 0x73, 0x57, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x67, 0x61, 0x73, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x61, 0x73, 0x46, 0x65, 0x65, 0x22, 0x5a, 0x0a, 0x0b, 0x54, 0x78, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x53, 0x65,
	0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_proto_tx_proto_rawDescOnce sync.Once
	file_models_proto_tx_proto_rawDescData = file_models_proto_tx_proto_rawDesc
)

func file_models_proto_tx_proto_rawDescGZIP() []byte {
	file_models_proto_tx_proto_rawDescOnce.Do(func() {
		file_models_proto_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_proto_tx_proto_rawDescData)
	})
	return file_models_proto_tx_proto_rawDescData
}

var file_models_proto_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_proto_tx_proto_goTypes = []any{
	(*Tx)(nil),              // 0: Tx
	(*TxFee)(nil),           // 1: TxFee
	(*TxSignature)(nil),     // 2: TxSignature
	(*PubKeySecp256K1)(nil), // 3: PubKeySecp256k1
	(*anypb.Any)(nil),       // 4: google.protobuf.Any
}
var file_models_proto_tx_proto_depIdxs = []int32{
	4, // 0: Tx.messages:type_name -> google.protobuf.Any
	1, // 1: Tx.fee:type_name -> TxFee
	2, // 2: Tx.signatures:type_name -> TxSignature
	4, // 3: TxSignature.pub_key:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_proto_tx_proto_init() }
func file_models_proto_tx_proto_init() {
	if File_models_proto_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_proto_tx_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Tx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_tx_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TxFee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_tx_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TxSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_proto_tx_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PubKeySecp256K1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_proto_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_tx_proto_goTypes,
		DependencyIndexes: file_models_proto_tx_proto_depIdxs,
		MessageInfos:      file_models_proto_tx_proto_msgTypes,
	}.Build()
	File_models_proto_tx_proto = out.File
	file_models_proto_tx_proto_rawDesc = nil
	file_models_proto_tx_proto_goTypes = nil
	file_models_proto_tx_proto_depIdxs = nil
}
